name: stripe_snowflake
version: '1.0.0'
config-version: 2

profile: stripe_snowflake

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  stripe_snowflake:
    staging:
      +schema: staging
      +materialized: view
      +tags: ["stripe", "staging"]
    core:
      +schema: core
      +materialized: table
      +tags: ["stripe", "core"]
