# scripts/verify-blueprint-003.ps1
# Blueprint #003 — Stripe → Snowflake Verification Script
#
# Production (default): requires real Stripe + Snowflake credentials —
#   STRIPE_API_KEY,
#   SNOWFLAKE_ACCOUNT, SNOWFLAKE_USER, SNOWFLAKE_PASSWORD,
#   SNOWFLAKE_DATABASE, SNOWFLAKE_WAREHOUSE
#
# -Local: no credentials needed. Stripe requires a real API, so local mode seeds
#   a DuckDB file with synthetic charges/customers generated by the RealityDB
#   pipelinekit-payments pack, then runs dbt against it — proving the
#   transform -> contract -> quality chain offline (same approach as
#   verify-blueprint-002.ps1).
#
# This script times each of the six standard steps. Record the result in
# blueprints/stripe-to-snowflake/docs/runbook.md (Verified Deployments).

param([switch]$Local)

$start = Get-Date

Write-Host "=== Blueprint #003 Verification ===" -ForegroundColor Cyan
Write-Host "Started: $start"

# Step 0: Preflight — required environment variables must be set.
if ($Local) {
    Write-Host "Mode: LOCAL (synthetic DuckDB — no Stripe/Snowflake creds)" -ForegroundColor Cyan
    $required = @()
} else {
    Write-Host "Mode: PRODUCTION (Stripe -> Snowflake)" -ForegroundColor Cyan
    $required = @("STRIPE_API_KEY",
                  "SNOWFLAKE_ACCOUNT", "SNOWFLAKE_USER", "SNOWFLAKE_PASSWORD",
                  "SNOWFLAKE_DATABASE", "SNOWFLAKE_WAREHOUSE")
}
$missing = $required | Where-Object { -not [Environment]::GetEnvironmentVariable($_) }
if ($missing) {
    Write-Host "✗ Missing env vars: $($missing -join ', ')" -ForegroundColor Red
    Write-Host "  Set all required variables before running this script."
    exit 1
}

# Step 1: Config + validate.
# The Blueprint #003 example.yaml uses the AI-proposed (non-standard) shape, so
# we write a standard pipelinekit.yaml that points contracts / transform / quality
# at the blueprint's own directories. Local mode uses a DuckDB destination.
$step1_start = Get-Date

$destination = if ($Local) {
@"
  destination:
    type: duckdb
    path: "pipelinekit_pipeline.duckdb"
"@
} else {
@"
  destination:
    type: snowflake
    account: "`${SNOWFLAKE_ACCOUNT}"
    database: "`${SNOWFLAKE_DATABASE}"
    user: "`${SNOWFLAKE_USER}"
    password: "`${SNOWFLAKE_PASSWORD}"
    warehouse: "`${SNOWFLAKE_WAREHOUSE}"
    schema: "raw"
"@
}

$config = @"
pipeline:
  name: stripe-to-snowflake
  version: "1.0.0"
  description: "Blueprint #003 — Stripe to Snowflake trusted analytics"

runtime:
  environment: local

ingestion:
  source:
    type: stripe
    api_key: "`${STRIPE_API_KEY}"
    tables:
      - charges
      - customers
$destination

transformation:
  enabled: true
  project_dir: ./blueprints/stripe-to-snowflake/transform

contracts:
  enabled: true
  directory: ./blueprints/stripe-to-snowflake/contracts

quality:
  enabled: true
  checks_dir: ./blueprints/stripe-to-snowflake/quality

diagnostics:
  enabled: true
  provider: anthropic

notifications:
  enabled: false
  channels: []
"@
Set-Content "pipelinekit.yaml" $config

if ($Local) {
    # dbt builds against the seeded local DuckDB file.
    $env:DBT_TARGET = "local"
    $env:DUCKDB_PATH = "pipelinekit_pipeline.duckdb"
    $env:DBT_SOURCE_DATABASE = "pipelinekit_pipeline"
    $env:DBT_SOURCE_SCHEMA = "pipelinekit_pipeline_raw"
}

poetry run pipelinekit validate
$step1_time = (New-TimeSpan -Start $step1_start -End (Get-Date)).TotalSeconds
Write-Host "Step 1 (config + validate): ${step1_time}s" -ForegroundColor Green

# Step 2: Blueprint validate.
$step2_start = Get-Date
poetry run pipelinekit blueprint validate stripe-to-snowflake
$step2_time = (New-TimeSpan -Start $step2_start -End (Get-Date)).TotalSeconds
Write-Host "Step 2 (blueprint validate): ${step2_time}s" -ForegroundColor Green

# Step 3: Dry run (production only — the Stripe ingestion adapter needs a live
# API; local mode seeds DuckDB directly in Step 4 instead).
$step3_start = Get-Date
if ($Local) {
    Write-Host "Step 3 (dry-run): skipped in local mode (no live Stripe source)" -ForegroundColor DarkGray
} else {
    poetry run pipelinekit run --dry-run
}
$step3_time = (New-TimeSpan -Start $step3_start -End (Get-Date)).TotalSeconds
Write-Host "Step 3 (dry-run): ${step3_time}s" -ForegroundColor Green

# Step 4: Full run.
$step4_start = Get-Date
if ($Local) {
    # 4a. Generate synthetic Stripe charges/customers from the RealityDB pack.
    node C:\Users\HP\Documents\databox\apps\cli\dist\index.js run `
        --pack C:\Users\HP\Documents\databox\apps\cli\src\packs\pipelinekit-payments.json `
        --rows 10000 --format sql --seed 42 `
        --output pipelinekit_payments_seed.sql

    # 4b. Load the seed into DuckDB under the dbt source schema. Tables are renamed
    #     to the source names the dbt staging models expect (charges, customers).
    $seed = @'
import duckdb

con = duckdb.connect("pipelinekit_pipeline.duckdb")
con.execute("CREATE SCHEMA IF NOT EXISTS pipelinekit_pipeline_raw")
# Read and execute the generated SQL (creates charges, customers, refunds).
sql = open("pipelinekit_payments_seed.sql").read()
con.execute(sql)
# Rename tables to match dbt source expectations (schema pipelinekit_pipeline_raw).
con.execute("CREATE OR REPLACE TABLE pipelinekit_pipeline_raw.charges AS SELECT * FROM charges")
con.execute("CREATE OR REPLACE TABLE pipelinekit_pipeline_raw.customers AS SELECT * FROM customers")
print("Seeded: customers and charges from pipelinekit-payments pack")
con.close()
'@
    $seed | poetry run python -

    # 4c. Transform the synthetic data through dbt (staging + core).
    poetry run dbt build `
        --project-dir blueprints/stripe-to-snowflake/transform `
        --profiles-dir blueprints/stripe-to-snowflake/transform `
        --target local
} else {
    poetry run pipelinekit run
}
$step4_time = (New-TimeSpan -Start $step4_start -End (Get-Date)).TotalSeconds
Write-Host "Step 4 (full run): ${step4_time}s" -ForegroundColor Green

# Step 5: Contract validation (loads and structurally validates the data
# contracts declared by the blueprint).
$step5_start = Get-Date
poetry run pipelinekit validate --contracts
$step5_time = (New-TimeSpan -Start $step5_start -End (Get-Date)).TotalSeconds
Write-Host "Step 5 (contract validation): ${step5_time}s" -ForegroundColor Green

# Step 6: Diagnose (production only — local mode performs no pipelinekit run, so
# there is no run in state to diagnose).
$step6_start = Get-Date
if ($Local) {
    Write-Host "Step 6 (diagnose): skipped in local mode (no pipelinekit run recorded)" -ForegroundColor DarkGray
} else {
    poetry run pipelinekit diagnose
}
$step6_time = (New-TimeSpan -Start $step6_start -End (Get-Date)).TotalSeconds
Write-Host "Step 6 (diagnose): ${step6_time}s" -ForegroundColor Green

$end = Get-Date
$total = ($end - $start).TotalMinutes

Write-Host ""
Write-Host "=== Verification Complete ===" -ForegroundColor Cyan
Write-Host "Total time: $([math]::Round($total, 1)) minutes"
Write-Host ""
Write-Host "Record this result in:"
Write-Host "blueprints/stripe-to-snowflake/docs/runbook.md"
Write-Host "Section: Verified Deployments"
